<?php
/**
 * Created by PhpStorm.
 * User: ronald
 * Date: 6/1/16
 * Time: 3:00 PM
 */

use Drupal\Core\Routing\RouteObjectInterface;

/**
 * Implements hook_theme().
 */
function apod_theme($existing, $type, $theme, $path)
{
    return array(
        'apod_content' => array(
            'template' => 'apod_content',
            'variables' => array(
                'title' => NULL,
                'image' => NULL,
                'image_date' => NULL,
                'links' => NULL,
                'description' => NULL,
            )
        ),
        'apod_image' => array(
            'template' => 'apod_image',
            'variables' => array(
                'item' => array(),
            ),
        ),
        'apod_video' => array(
            'template' => 'apod_video',
            'variables' => array(
                'item' => array(),
            ),
        ),
    );
}

/**
 * Implements hook_preprocess_html().
 *
 * Add custom
 */
function apod_preprocess_html(&$variables)
{
    $route = \Drupal::request()->get(RouteObjectInterface::ROUTE_NAME);
    if ($route == 'apod.default_page' || $route == 'apod.date_page') {
        $variables['attributes']['class'][] = 'page-astronomy-picture-of-the-day';
    }
}

function apod_preprocess_page(&$variables)
{
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function apod_theme_suggestions_alter(array &$suggestions, array $variables, $hook)
{
    $route = \Drupal::request()->get(RouteObjectInterface::ROUTE_NAME);
    if ($route == 'apod.default_page' || $route == 'apod.date_page') {
        $base = \Drupal::service('extension.path.resolver')->getPath('apod') . '/templates/';
        $suggestions[] = $base . $hook . '__apod_default';
        $suggestions[] = $base . $hook . '__apod';
        $suggestions[] = $hook . '__apod_default';
        $suggestions[] = $hook . '__apod';
    }
}

